### ISSUE TITLE
Start running a load balancer and two servers / sets of services (A/B) so deploying a new version of the site doesn't bring everything down. Also, run a UAT server!

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/demsausage#1337]
[AB#8](https://dev.azure.com/contentsmaydiffer/cbcb376c-170c-4145-a81c-387d82266f0d/_workitems/edit/8)

**Comment by MrMadium** [comment]
Noting that you're currently running on S3 - if you needed to rectify this today could you migrate to AWS Beanstalk?

That will take care of Load Balancing, multi-availability zones, redundancy and scale requirements.

Note: I am a student and have no idea what I am doing.

**Comment by keithamoss** [comment]
Hey, thanks for the comment @MrMadium! :)

Some of the doco in the README is woefully out of date. We've since moved to DigitalOcean + CloudFlare (caching layer).

We've had no problems with load today fortunately, since a lot of the content and data gets served out of either CloudFront, or from NGinx with a Memcached layer in front. So not much actually hits the application or the database, thankfully! s😅

**Comment by keithamoss** [comment]
Staging service is now setup, calling this one closed.
