### ISSUE TITLE
Give stalls and polling places on the public site permanent URLs

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/demsausage#18]
Right now ourselves and users can't link to stalls or polling places directly, only to elections. We should be able to link to the polling place details card through a permanent URL like:

https://democracysausage.org/victorian_election_2018/polling_places/Name/Premises/State
https://democracysausage.org/victorian_election_2018/polling_places/ec_id (where available - depends on the electoral commissions)

And to stalls through a permanent URL like:

https://democracysausage.org/victorian_election_2018/stalls/stall_id

Using the polling place name as the unique key will avoid issues with the polling place ids changing and make integration by third parties easier (no ids to update, and they'll have this info anyway).

# Issues
Polling places: Upon investigation, combining name, premises, and state is the only way to get a globally unique polling place identifier. Proposed URL format revised.

# Considerations
- Poling places: Do we only support polling place name or premises as well? We could support both under the same URL and just try name first?
- Polling places: Polling place name is unlikely to change after the initial load, but premises name may. This makes it not really a permanent URL, but close enough for our needs.

# Design
- Both URLs will end up at the same UI screen, but will fetch their polling place info differently.
- The UI should display a "View on map" button.
- If a stall is is still pending its link will work, but we'll just display the standard "We don't know anything about this polling place yet" message.
- We'll need a nice error state for "Couldn't find polling place" to catch edge cases where the polling place name / premises changes.
- People submitting stalls should receive a link to their stall in the "stall approved" email
- Users should be able to get a link to a polling place when they query it
- Admins should be able to get a link to a stall when they're approving it
- Admins should should be able to get a link to a polling place when they're editing it or viewing the favourites list

# Test URLs
## Web UI
https://test.democracysausage.org/federal_election_2019/polling_places/Bayswater%20North/Hillcrest%20Primary%20School/WA/

https://test.democracysausage.org/federal_election_2019/polling_places/8143

https://test.democracysausage.org/federal_election_2019/stalls/1000

## API
https://test.democracysausage.org/api/0.1/polling_places/lookup/?election_id=27&format=json&name=Bayswater%20North&premises=Hillcrest%20Primary%20School&state=WA

https://test.democracysausage.org/api/0.1/polling_places/lookup/?election_id=27&format=json&ec_id=8143

https://test.democracysausage.org/api/0.1/polling_places/stall_lookup/?format=json&stall_id=1040

**Comment by ineffyble** [comment]
This is very relevant for external integrations - it would be great if an external site could link a user through directly to the relevant stall.

**Comment by keithamoss** [comment]
> This is very relevant for external integrations - it would be great if an external site could link a user through directly to the relevant stall.

@ineffyble This is live now.

https://democracysausage.org/federal_election_2019/polling_places/Bayswater%20North/Hillcrest%20Primary%20School/WA/

https://democracysausage.org/federal_election_2019/polling_places/8143

https://democracysausage.org/federal_election_2019/stalls/1000

**Comment by ineffyble** [comment]
@keithamoss Will do this weekend. For analytics/stats, would it be helpful if the links included a referrer URL query parameter? (e.g. `referrer=GreensHTV` or `utm_source=greens&utm_campaign=htv`)

**Comment by keithamoss** [comment]
@ineffyble That would be handy! Google Analytics should give us referer information from headers, but more detail is always good.

**Comment by ineffyble** [comment]
@keithamoss Done! You should start seeing hits to links such as https://democracysausage.org/federal_election_2019/polling_places/5105?referrer=GreensHowToVote

**Comment by keithamoss** [comment]
Yup, I see them now - 12 since you added the referrer. Thanks!

And you're right, GAnalytics isn't picking up the referrer from the header thanks to `noreferrer`.
