### ISSUE TITLE
Alternatives to `SwipeableDrawer`

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/demsausage#1848]
We're using MUI's `SwipeableDrawer` at the moment, but we've had to hack it a bit to make the contents interactable (buttons, form fields, et cetera) at the time of writing it also has a few unfixed bugs that might cause us headaches in production.

Have another look at these issues and consider the below options.

[How can I achieve this gesture behavior using vanilla JS, HTML, and CSS?](https://www.reddit.com/r/webdev/comments/v5ccf2/how_can_i_achieve_this_gesture_behavior_using/)

https://reactjsexample.com/tag/bottom-sheet/

**Historical stuff on the React Spring attempt**
https://github.com/stipsan/react-spring-bottom-sheet/blob/main/GET_STARTED.md#get-started

https://github.com/stipsan/react-spring-bottom-sheet/issues/210

https://github.com/stipsan/react-spring-bottom-sheet/blob/main/src/BottomSheet.tsx

[AB#146](https://dev.azure.com/contentsmaydiffer/cbcb376c-170c-4145-a81c-387d82266f0d/_workitems/edit/146)

**Comment by ramirez411** [comment]
I´m trying with this:
[https://www.npmjs.com/package/react-modal-sheet](url)
