### ISSUE TITLE
Add endpoint for all polling places for election (alternatively, include stall name in map API endpoint)

### ISSUE THREAD

**Issue by ineffyble** [keithamoss/demsausage#56]
I was able to link our dataset to Democracy Sausage's quite easily, without spamming the Democracy Sausage API, by pulling the /map endpoint and matching on coordinates.

However, this hasn't been perfect - there's a couple of hundred polling places that weren't linked, and upon inspection have differing coordinates between our systems.

If there was a /polling_places/all endpoint, this would work nicely and allow the most thorough matching.

Alternatively, if the /map endpoint included polling place name, this could be used as another way to match polling places.

**Comment by keithamoss** [comment]
Hey Effy, thanks for the interest - let's have a think about the best way to do this.

Does your integration need to display sausage status in a list form (e.g. all polling places, or all polling places for a particular division) or is it only on a per-polling place basis?

We've already got a `/polling_places/all` sort of endpoint for internal use, so exposing that is easy. It's a little db intensive - particularly for a Federal election - so we've kept it private for now. If I was to expose it I'd probably add in API keys so we can throttle/blacklist anyone who abuses it.

I'm trying to keep the `/map` endpoint's size to an absolute minimum to keep map load times for users super speedy.

By the way - we have API [documentation over here](https://democracysausage.org/api/0.1/swagger/).

The mismatches between your polling places and ours may just be a case of when we both pulled the data from the NSW Electoral Commission. We loaded ours on March 1st.

**Comment by ineffyble** [comment]
It's per polling place. We already show all the polling places on a map, it's just a case of adding the additional data.

What I currently did was hit the map endpoint, download the entire json, perform matching, and add a democracy_sausage_id to all matched polling places. 

When a client hits our API to get the polling places for an electorate, our API gets all the democracy_sausage_ids and hits your search endpoint, adding the resulting data back to the polling places before sending them to our client. 

Mismatches might be that, but I think it's more likely just geocoding inconsistencies.

I found the Swagger, very helpful.

My integration wouldn't need to hit /all regularly - even just a once off dump now would be perfect.

**Comment by keithamoss** [comment]
Neat approach - one caveat to be aware of with doing that is that our polling place ids aren't immutable. They'll all change each time we do an ingest and update with new data from the electoral commission. That doesn't happen often, only a couple of times for each election, but when it does it'll mean all of your `/polling_places/search/` queries will start returning 0 results for any query you send it using the old ids.

That's a little suboptimal for you :)

What if we allowed searching by polling place names on `/polling_place/search/`? Does that remove the need for you to match and store `democracy_sausage_id`?

**Comment by ineffyble** [comment]
I believe you already can search by individual names. But I'd need to be able to give a list of names (same way you can give a list of IDs), or hit the API once per place instead of just once. But yes, that would work well I think.

**Comment by keithamoss** [comment]
Sort of - the `search_term` param returns any polling places with a name, premises, or address that contains the search term (case insensitive).

That returns a single polling place in most cases, but common words - or parts of words - get a bit messy. e.g. `ACON` https://democracysausage.org/api/0.1/polling_places/search/?election_id=26&format=json&search_term=ACON

OK, so we'll add a `polling_place_names` parameter to `/polling_places/search/` that accepts a comma separated list of polling place names. I should have time to tackle that Tuesday/Wednesday this week - will keep you in the loop.

**Comment by keithamoss** [comment]
Alternatively, if you'd like to get your hands dirty a PR would be most welcome :)

**Comment by keithamoss** [comment]
FYI I've also included the polling place name in the GeoJSON `/map/` API endpoint now. In doing that the structure of the `properties` for each polling place has changed a little.

From this:

```json
{
      "id": 37575,
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          151.155831,
          -33.901247
        ]
      },
      "properties": {
        "bbq": true,
        "cake": true,
        "nothing": false,
        "run_out": false,
        "other": true
      }
    }
```

to this:

```json
{
      "id": 37575,
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          151.155831,
          -33.901247
        ]
      },
      "properties": {
        "noms": {
          "bbq": true,
          "cake": true,
          "nothing": false,
          "run_out": false,
          "other": true
        },
        "name": "Wilkins Public School"
      }
    }
```

**Comment by ineffyble** [comment]
@keithamoss Beautiful, thank you. I just tested matching by coords or name, and I'm down to literally 4 places across the entire state.

**Comment by ineffyble** [comment]
@keithamoss The following request (via either Swagger or a HTTP request in my Lambda) is giving a 502:

```
curl -X GET "https://democracysausage.org/api/0.1/polling_places/search/?polling_place_names=Balmain%20Election%20Manager's%20Office%2CAnnandale%20North%20Public%20School%2CJimmy%20Little%20Community%20Centre%2CLeichhardt%20Town%20Hall%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2CLeichhardt%20Town%20Hall%2CSydney%20Secondary%20College%20-%20Balmain%20Campus%2CSydney%20Secondary%20College%20-%20Leichhardt%20Campus%2CJimmy%20Little%20Community%20Centre%2CSt%20Fiacres%20Church%20Hall%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2CInner%20Sydney%20Montessori%20School%2CBalmain%20Election%20Manager's%20Office%2CSydney%20Town%20Hall%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2CSydney%20Secondary%20College%20-%20Leichhardt%20Campus%2CAnnandale%20North%20Public%20School%2CSt%20Scholasticas%20College%2CLeichhardt%20Town%20Hall%2CSt%20Barnabas%20Church%20Broadway%2CSydney%20Town%20Hall%2CBirchgrove%20Public%20School%2CBalmain%20Election%20Manager's%20Office%2CSt%20Fiacres%20Church%20Hall%2CBalmain%20Hospital%2CGlebe%20Town%20Hall%2CLeichhardt%20Town%20Hall%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Hospital%2CLeichhardt%20Town%20Hall%2CInner%20Sydney%20Montessori%20School%2CBalmain%20Election%20Manager's%20Office%2CSydney%20Town%20Hall%2CLeichhardt%20Town%20Hall%2CForest%20Lodge%20Public%20School%2CSt%20Barnabas%20Church%20Broadway%2CAnnandale%20Public%20School%2CGlebe%20Town%20Hall%2CSt%20Barnabas%20Church%20Broadway%2CBalmain%20Election%20Manager's%20Office%2CLeichhardt%20Town%20Hall%2CSt%20Barnabas%20Church%20Broadway%2CLeichhardt%20Town%20Hall%2CSydney%20Town%20Hall%2CRozelle%20Public%20School%2CKegworth%20Public%20School%2CSt%20Barnabas%20Church%20Broadway%2CKegworth%20Public%20School%2CPeter%20Forsyth%20Auditorium%2CSt%20Barnabas%20Church%20Broadway%2CSydney%20Town%20Hall%2CSydney%20Town%20Hall%2CSydney%20Town%20Hall%2CSydney%20Town%20Hall%2CNicholson%20Street%20Public%20School%2CSt%20Scholasticas%20College%2CSt%20Barnabas%20Church%20Broadway%2CSt%20Barnabas%20Church%20Broadway%2CLeichhardt%20Town%20Hall%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2COrange%20Grove%20Public%20School%2CBalmain%20Public%20School%2CSydney%20Secondary%20College%20Blackwattle%20Bay%20Campus%2CBalmain%20Election%20Manager's%20Office%2CRozelle%20Public%20School%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2CBalmain%20Election%20Manager's%20Office%2CSt%20Barnabas%20Church%20Broadway%2CBalmain%20Election%20Manager's%20Office%2CLeichhardt%20Town%20Hall%2CForest%20Lodge%20Public%20School%2CSt%20Barnabas%20Church%20Broadway%2CBalmain%20Election%20Manager's%20Office%2CUltimo%20Public%20School%2CSydney%20Secondary%20College%20Blackwattle%20Bay%20Campus%2CLeichhardt%20Town%20Hall%2CSydney%20Secondary%20College%20-%20Balmain%20Campus%2COrange%20Grove%20Public%20School%2CSydney%20Town%20Hall%2CBalmain%20Public%20School%2CLeichhardt%20Town%20Hall%2CSt%20Barnabas%20Church%20Broadway%2CBalmain%20Election%20Manager's%20Office%2CSt%20Barnabas%20Church%20Broadway%2CPeter%20Forsyth%20Auditorium%2CLeichhardt%20Town%20Hall%2CSydney%20Town%20Hall%2CBirchgrove%20Public%20School%2CNicholson%20Street%20Public%20School&election_id=26" -H "accept: application/json" -H "X-CSRFToken: nq8El2hvb4UxJeC1W8Bcxfa1s0E54eZHDAD9TZ2aN29jn2B7k4cCuA3Mk9ocxrkq"
```

**Comment by keithamoss** [comment]
OK, that's fixed now.

By default UWSGI only accepts requests with headers up to 4096 bytes in length. I've doubled that now, so you should be good.

**Comment by ineffyble** [comment]
@keithamoss I can confirm that's working! Thank you for your help.
