### ISSUE TITLE
Intermittent API errors

### ISSUE THREAD

**Issue by ineffyble** [keithamoss/demsausage#77]
Occasionally when performing a request like

```
https://democracysausage.org/api/0.1/polling_places/search/?polling_place_names=Merri%2CCoburg%20North%2CPascoe%20Vale%20Central%2CGlenroy%20North%2CHadfield%2CFawkner%20East%2CGlenroy%20PPVC%2CPascoe%20Vale%20North%2CGlenroy%2CMitchell%2CPascoe%20Vale%2CCoburg%20East%2CCoburg%20West%2CStrathmore%20North%2CBrunswick%20North%20East%2CMelville%2CBrunswick%20South%20West%2CMoreland%2CGlenroy%20West%2CFawkner%20North%2CBrunswick%20South%2CBrunswick%20East%2CMurray%2CMerlynston%2CPascoe%20Vale%20West%2CGowrie%20Park%2CAnstey%2CPascoe%20Vale%20South%2CMelbourne%2CLake%20Park%2CCoburg%2CBrunswick%20North%2CBrunswick%20North%20West%2COak%20Park%2CMoomba%20Park%2CGaffney%2CCoburg%20South%2CBrunswick%20South%20East&election_id=27
```

I get a response of:

```
{ detail: 'Please supply at least one value to filter by' }
```

I suspect this is related to caching or such, because this error seems to occur after we haven't polled DS for a while (or at least, for that electorate), and then can't be reproduced immediately after, even if I hit the same URL a dozen times.

[AB#100](https://dev.azure.com/contentsmaydiffer/cbcb376c-170c-4145-a81c-387d82266f0d/_workitems/edit/100)

**Comment by keithamoss** [comment]
I've had a look through the logs for the past few days and the only occurrences of HTTP 400 Bad Request errors are for calls like `https://test.democracysausage.org/api/0.1/polling_places/search/?polling_place_names=&election_id=27&format=json` which legit raise a 400 error with that message.

There's nowhere between you and the database that I can think of on `/polling_places/search/` endpoint either.

I take it you're seeing these in your backend ingest process? If you can let me know what IP address that's running from I can take a closer look at the logs.

**Comment by ineffyble** [comment]
Hmm, it's being called from an AWS Lambda function so there's no IP I can give you. 

I'll add debug logging and get some more info.

**Comment by keithamoss** [comment]
Ahh - attaching an extra URL query param would also do the trick.

**Comment by keithamoss** [comment]
@ineffyble Did you keep receiving these intermittent errors in the lead up to the election? (Apart from the hiccup on the day of the election itself)
